name: Lint

on: [push, pull_request]

jobs:
  pylint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: pip install pylint yapf
      - name: Run pylint
        run: pylint ./png.py
      - name: Auto-fix formatting (Optional)
        if: github.event_name == 'push'
        run: yapf ./png.py --in-place     